export enum ErrorCode {
  // Authentication & Authorization errors
  INVALID_EMAIL = 'INVALID_EMAIL',
  EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  EMAIL_ALREADY_EXIST = 'EMAIL_ALREADY_EXIST',
  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_MISSING = 'TOKEN_MISSING',
  TOKEN_REVOKED = 'TOKEN_REVOKED',
  ACCESS_DENIED = 'ACCESS_DENIED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_DISABLED = 'USER_DISABLED',
  UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
  AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED',
  SESSION_EXPIRED = 'SESSION_EXPIRED',

  // User management errors
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_CREATION_FAILED = 'USER_CREATION_FAILED',
  USER_UPDATE_FAILED = 'USER_UPDATE_FAILED',
  USER_DELETION_FAILED = 'USER_DELETION_FAILED',
  INVALID_USER_ROLE = 'INVALID_USER_ROLE',
  WEAK_PASSWORD = 'WEAK_PASSWORD',
  INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT',
  TELEPHONE_INVALID = 'TELEPHONE_INVALID',
  TELEPHONE_ALREADY_EXIST = 'TELEPHONE_ALREADY_EXIST',
  INDICATEUR_INVALIDE = 'INDICATEUR_INVALIDE',
  TELEPHONE_FORMAT_INVALID = 'TELEPHONE_FORMAT_INVALID',
  TELEPHONE_NOT_VERIFIED = 'TELEPHONE_NOT_VERIFIED',
  TELEPHONE_ALREADY_VERIFIED = 'TELEPHONE_ALREADY_VERIFIED',
  OTP_INVALID = 'OTP_INVALID',
  OTP_EXPIRED = 'OTP_EXPIRED',
  EMAIL_ALREADY_VERIFIED = 'EMAIL_ALREADY_VERIFIED',

  // Course management errors
  COURSE_NOT_FOUND = 'COURSE_NOT_FOUND',
  COURSE_CREATION_FAILED = 'COURSE_CREATION_FAILED',
  COURSE_UPDATE_FAILED = 'COURSE_UPDATE_FAILED',
  COURSE_DELETION_FAILED = 'COURSE_DELETION_FAILED',
  COURSE_ALREADY_ENROLLED = 'COURSE_ALREADY_ENROLLED',
  COURSE_NOT_ENROLLED = 'COURSE_NOT_ENROLLED',
  INVALID_COURSE_STATUS = 'INVALID_COURSE_STATUS',
  COURSE_ACCESS_DENIED = 'COURSE_ACCESS_DENIED',
  COURSE_LIMIT_EXCEEDED = 'COURSE_LIMIT_EXCEEDED',

  // Lesson & Module errors
  LESSON_NOT_FOUND = 'LESSON_NOT_FOUND',
  LESSON_CREATION_FAILED = 'LESSON_CREATION_FAILED',
  LESSON_UPDATE_FAILED = 'LESSON_UPDATE_FAILED',
  LESSON_DELETION_FAILED = 'LESSON_DELETION_FAILED',
  MODULE_NOT_FOUND = 'MODULE_NOT_FOUND',
  MODULE_CREATION_FAILED = 'MODULE_CREATION_FAILED',
  MODULE_UPDATE_FAILED = 'MODULE_UPDATE_FAILED',
  MODULE_DELETION_FAILED = 'MODULE_DELETION_FAILED',
  INVALID_LESSON_ORDER = 'INVALID_LESSON_ORDER',
  INVALID_MODULE_ORDER = 'INVALID_MODULE_ORDER',

  // Enrollment errors
  ENROLLMENT_NOT_FOUND = 'ENROLLMENT_NOT_FOUND',
  ENROLLMENT_FAILED = 'ENROLLMENT_FAILED',
  ENROLLMENT_CANCELLED = 'ENROLLMENT_CANCELLED',
  DUPLICATE_ENROLLMENT = 'DUPLICATE_ENROLLMENT',
  ENROLLMENT_EXPIRED = 'ENROLLMENT_EXPIRED',
  INVALID_ENROLLMENT_STATUS = 'INVALID_ENROLLMENT_STATUS',

  // Payment errors
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  INVALID_PAYMENT_AMOUNT = 'INVALID_PAYMENT_AMOUNT',
  PAYMENT_GATEWAY_ERROR = 'PAYMENT_GATEWAY_ERROR',
  PAYMENT_CANCELLED = 'PAYMENT_CANCELLED',
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  PAYMENT_TIMEOUT = 'PAYMENT_TIMEOUT',
  DUPLICATE_PAYMENT = 'DUPLICATE_PAYMENT',

  // Quiz & Assessment errors
  QUIZ_NOT_FOUND = 'QUIZ_NOT_FOUND',
  QUIZ_CREATION_FAILED = 'QUIZ_CREATION_FAILED',
  QUIZ_UPDATE_FAILED = 'QUIZ_UPDATE_FAILED',
  QUIZ_DELETION_FAILED = 'QUIZ_DELETION_FAILED',
  QUIZ_ALREADY_TAKEN = 'QUIZ_ALREADY_TAKEN',
  QUIZ_TIME_EXPIRED = 'QUIZ_TIME_EXPIRED',
  INVALID_QUIZ_ANSWERS = 'INVALID_QUIZ_ANSWERS',
  QUIZ_ATTEMPT_NOT_FOUND = 'QUIZ_ATTEMPT_NOT_FOUND',
  QUESTION_NOT_FOUND = 'QUESTION_NOT_FOUND',
  INVALID_QUESTION_TYPE = 'INVALID_QUESTION_TYPE',

  // File & Storage errors
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  INVALID_FILE_FORMAT = 'INVALID_FILE_FORMAT',
  STORAGE_QUOTA_EXCEEDED = 'STORAGE_QUOTA_EXCEEDED',
  FILE_DELETION_FAILED = 'FILE_DELETION_FAILED',
  FILE_ACCESS_DENIED = 'FILE_ACCESS_DENIED',

  // Certificate errors
  CERTIFICATE_NOT_FOUND = 'CERTIFICATE_NOT_FOUND',
  CERTIFICATE_GENERATION_FAILED = 'CERTIFICATE_GENERATION_FAILED',
  CERTIFICATE_ALREADY_ISSUED = 'CERTIFICATE_ALREADY_ISSUED',
  INVALID_CERTIFICATE_DATA = 'INVALID_CERTIFICATE_DATA',
  CERTIFICATE_VERIFICATION_FAILED = 'CERTIFICATE_VERIFICATION_FAILED',

  // Validation errors
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  INVALID_INPUT = 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',
  INVALID_DATA_TYPE = 'INVALID_DATA_TYPE',
  VALUE_OUT_OF_RANGE = 'VALUE_OUT_OF_RANGE',
  INVALID_FORMAT = 'INVALID_FORMAT',

  // System errors
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  CONFIGURATION_ERROR = 'CONFIGURATION_ERROR',
  DEPENDENCY_ERROR = 'DEPENDENCY_ERROR',

  // Rate limiting errors
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',

  // Business logic errors
  BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION',
  OPERATION_NOT_ALLOWED = 'OPERATION_NOT_ALLOWED',
  RESOURCE_LOCKED = 'RESOURCE_LOCKED',
  CONFLICTING_OPERATION = 'CONFLICTING_OPERATION',

  // Marketplace
  CATEGORIE_SHOP_NOT_FOUND = 'CATEGORIE_SHOP_NOT_FOUND',
  CATEGORIE_SHOP_ALREADY_EXISTS = 'CATEGORIE_SHOP_ALREADY_EXISTS',
  CATEGORIE_PROD_NOT_FOUND = 'CATEGORIE_PROD_NOT_FOUND',
  CATEGORIE_PROD_ALREADY_EXISTS = 'CATEGORIE_PROD_ALREADY_EXISTS',
}
